new fix

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -66,7 +66,10 @@ jobs:
               echo "Warning: Failed to clean $NGINX_FRONTEND_ROOT. Proceeding with copy."
             }
             cd "$NGINX_FRONTEND_ROOT"
-            cat new.html
+            mkdir Hello || {
+            echo "Error: Failed to create 'Hello' directory."
+              exit 1
+            }
             echo "Clean up complete."
           source: "${{ github.workspace }}/dist/."
           target: "${{ secrets.VPS_REMOTE_PATH }}"
