new fix

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -65,11 +65,11 @@ jobs:
               exit 1
             }
 
-            echo "Cleaning existing files in $NGINX_FRONTEND_ROOT"
-            rm -rf "${NGINX_FRONTEND_ROOT:?}"/* || {
-              echo "Warning: Failed to clean $NGINX_FRONTEND_ROOT. Proceeding with copy."
-            }
-            echo "Clean up complete."
+            #echo "Cleaning existing files in $NGINX_FRONTEND_ROOT"
+            #rm -rf "${NGINX_FRONTEND_ROOT:?}"/* || {
+            #  echo "Warning: Failed to clean $NGINX_FRONTEND_ROOT. Proceeding with copy."
+            #}
+            #echo "Clean up complete."
           source: "${{ github.workspace }}/dist/."
           target: "${{ secrets.VPS_REMOTE_PATH }}"
           overwrite: true 
